# -*- coding: utf-8 -*-
"""Aula2_String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1al8CmXbxJeQK80VVaK-ZhmlP_mtzZ_rI

Primeiro código em Python!!!
"""

print('Olá mundo!!!')
print()
print('Eu fiz meu primeiro código em Python. Eba!!!')
print()
print('Esse código vai dar erro!')

"""Chamando uma variável do tipo String(Blue), Inteiro(25) e Float(15.87)"""

print('Olá mundo!!!')
print()
var1 = 'Blue'
var2 = 25
var3 = 15.87

print(var1)
print(var2)
print(var3)

var1 = 250
var1a = 100
var2 = "250"
var2a = "100"
var3 = 'Batman que ri" do quadrinho'
var4 = "de um universo paralelo"
# concatenação 

print(type(var1))
print(type(var2))
print()
print(var2 + var2a)
# print(concatenação)