# -*- coding: utf-8 -*-
"""EXERCICO CAIXA REGISTRADORA AULA 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wCnhNrikqvoAW9vsB3QvGeFM9e7Gnoxg
"""

#Caixa eletrônico
#Faça um Programa para um caixa eletrônico. O programa deverá perguntar ao usuário a valor do saque e depois informar quantas notas de cada valor serão fornecidas.
#As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais.
#O valor mínimo é de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a quantidade de notas existentes na máquina.
#Exemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de 100, uma nota de 50, uma nota de 5 e uma nota de 1;
#Exemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de 100, uma nota de 50, quatro notas de 10, uma nota de 5 e quatro notas de 1.


var1 = 100
var2 = 50
var3 = 10
var4 = 5
var5 = 1

quant100 = 0
quant50 = 0
quant10 = 0
quant5 = 0
quant1 = 0

valor= float(input('Digite o valor do SAQUE: ')) 
while valor > 600 or valor < 10:
 valor = float(input('VALOR NEGADO, FAVOR INFORMAR NOVO VALOR MENOR QUE 600 OU MAIOR QUE 10:  ')) 

quant_aux = valor

quant100 = quant_aux//100
quant_aux = quant_aux - (quant100*100) 

quant50 = quant_aux//50
quant_aux = quant_aux - (quant50*50) 

quant10 = quant_aux//10
quant_aux = quant_aux - (quant10*10) 

quant5 = quant_aux//5
quant_aux = quant_aux - (quant5*5) 

quant1 = quant_aux//1
quant_aux = quant_aux - (quant1*1) 

print (valor)
print( f' {quant100} NOTAS DE 100')
print( f' {quant50} NOTAS DE 50')
print( f' {quant10} NOTAS DE 10')
print( f' {quant5} NOTAS DE 5')
print( f' {quant1} NOTAS DE 1')
print(quant_aux)