# -*- coding: utf-8 -*-
"""Aula 01 - Variáveis, Print, Input e Operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMdMImHBnif-AAvdFU_iQBX4-KK4Ywa-

# Sintaxe elegante, simples e clara

Permite fácil legibilidade do código-fonte.
A simplicidade torna a linguagem menos verbosa.
Linguagem ideal para scripts.
Desenvolvimento rápido.
"""

print('Olá mundo!!!')

x = 'Blue'
print(x)

"""Tipagem dinâmica.


"""

# #Criação de variável inteira
# #x = 1
# print(x)

# #Criação de variável String
# x = 'A'
# print(x)

b = 10
t = 20
print(f'resultado: {b + t}')

# Criando várias variáveis

var_a, var_b, var_c = 10, 10.78, 'Blue'
print(var_a)
print(var_b)
print(var_c)
print()

#Printando vários valores
print(var_a, var_b, var_c)