# -*- coding: utf-8 -*-
"""exec alunos1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F7RYqNQ75FD41Muy4ZrrQSjMGIYdXhpC
"""

def somar(n1,n2,n3):
    soma = n1 + n2 + n3
    return soma
num1 = int(input('Digite o primeiro numero: '))
num2 = int(input('Digite o segundo numero: '))
num3 = int(input('Digite o terceiro numero: '))
final = somar(num1,num2,num3)
print(final)
#acho que ta igual o primeiro

def funcao(num1):
    if num1 > 0:
        positivo = 'P'
        return positivo
    elif num1 < 0:
        negativo = 'N'
        return negativo
    else:
        igual = '0'
        return igual

numero = int(input('Digite um numero: '))
print(funcao(numero))
# o terceiro ainda não terminei
# é um pouco mais complicado rsrs

def dateString(data):
    from datetime import date
    convertData = data.split('/')
    ano = int(convertData[2])
    mes = int(convertData[1])
    dia = int(convertData[0])
    dataTeste = date(ano, mes, dia)
    print(f'{dataTeste.day} de {dataTeste.month} de {dataTeste.year}')

dateString('10/08/2020')